![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.19.4


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [3]:
# your code goes here
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [7]:
# your code goes here
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [13]:
# your code goes here
np.ones(dtype=np.int,shape=(2,2))

array([[1, 1],
       [1, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [14]:
# your code goes here
np.ones(shape=(3,2), dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [21]:
# your code goes here
x = np.arange(4, dtype=np.int)
y = np.ones_like(x)
y

array([1, 1, 1, 1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [27]:
# your code goes here
x = np.array([[3,4],[4,5]] , dtype=np.int)
y = np.zeros_like(x)
y

array([[0, 0],
       [0, 0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [29]:
# your code goes here
np.ones([4,4], dtype=np.int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [30]:
# your code goes here
x = np.array([[3,4,5],[6,7,8]], dtype = np.int)
y = np.ones_like(x) * 7
y

array([[7, 7, 7],
       [7, 7, 7]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [31]:
# your code goes here
x = np.identity(3, dtype=np.int)
x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [32]:
# your code goes here
np.random.randint(low=1, high=10, size=3)

array([3, 8, 5])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [34]:
# your code goes here
np.random.randn(3,3,3)

array([[[ 1.16228069,  0.67486147, -0.71549751],
        [ 2.65987979,  0.71615061,  0.75081155],
        [-0.03975511, -0.14263104, -0.81178305]],

       [[ 0.29908656, -0.02844429, -0.68171298],
        [-0.50930372,  0.04520765,  1.01126126],
        [-0.83784415, -0.24851579,  1.87942072]],

       [[-0.84685907,  1.41841817,  0.22699697],
        [ 0.49992904, -0.54907158,  2.16996612],
        [ 0.34056153, -1.84272866, -0.63896109]]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [37]:
# your code goes here
x = [1,2,3,4]
y = np.array(x)
y

array([1, 2, 3, 4])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [39]:
# your code goes here
x = np.array([1,2,3,4,4])
y = np.copy(x)
y 

array([1, 2, 3, 4, 4])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

In [41]:
# your code goes here
x = np.arange(1,11, dtype=np.int)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

In [47]:
# your code goes here
x = np.arange(1,11, dtype = np.int, )
y = x[x%2 != 0]
y

# or
x = np.arange(1,11,step=2)
x

array([1, 3, 5, 7, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

In [54]:
# your code goes here
x = np.arange(1,11)
y = x[::-1]
y

#or
x = np.arange(1,11)[::-1]
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [60]:
# your code goes here
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

In [ ]:
# your code goes here


In [ ]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [61]:
# your code goes here
X = np.array([1,2,3,4], dtype = np.int)
x[0]

10

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

In [62]:
# your code goes here
X = np.array(['A','B','C'], dtype=np.str)
X[-1]

'C'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

In [64]:
# your code goes here
X = np.array([1,2,3,4,5,6,7,8,9,10], dtype = np.int)
X[:3]

array([1, 2, 3])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements

In [71]:
# your code goes here
X = np.array([1,2,3,4,5,6,7,8,9,10], dtype = np.int)
X[1:-1]

array([2, 3, 4, 5, 6, 7, 8, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [73]:
# your code goes here
X = np.array([1,2,3,4,5,6,7,8,9,10], dtype = np.int)
X[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in an odd position

In [76]:
# your code goes here
X = np.array([1,2,3,4,5,6,7,8,9,10], dtype = np.int)
X[X%2 != 0]

array([1, 3, 5, 7, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

In [78]:
# your code goes here
X = np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9]], 
  dtype = np.int)

X[0]

array([1, 2, 3])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [79]:
# your code goes here
X = np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9]], 
  dtype = np.int)

X[-1]

array([7, 8, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [81]:
# your code goes here
X = np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9]], 
  dtype = np.int)

X[0,0] # or x[0][0] of course!

1

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [84]:
# your code goes here
X = np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9]], 
  dtype = np.int)

X[-1,-1] # or X[-1][-1]

9

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [89]:
# your code goes here
X = np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9]], 
  dtype = np.int)

X[1:-1,1:-1]

array([[5]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [90]:
# your code goes here
X = np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9]], 
  dtype = np.int)

X[:2,:2]

array([[1, 2],
       [4, 5]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [99]:
# your code goes here
X = np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9]], 
  dtype = np.int)

X[-2:,-2:]

array([[5, 6],
       [8, 9]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [102]:
# your code goes here
x = np.array([1,3,5], dtype = np.int)
y = np.array(x, dtype=np.float)
y

array([1., 3., 5.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [104]:
# your code goes here
x = np.array([1,3,4,5,6,7,8,9], dtype=np.int)
x = x[::-1]
x

array([9, 8, 7, 6, 5, 4, 3, 1])

In [ ]:
X = [-5, -3, 0, 10, 40]

X[::-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [107]:
# your code goes here
x = np.array([2,3,4,10,4,1,-1], dtype = np.int)
x.sort()
x

array([-1,  1,  2,  3,  4,  4, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, set the fifth element equal to 1

In [109]:
# your code goes here
x = np.array([1,2,3,60,3,1,46,1010], dtype = np.int)
x[4] = 1
x

array([   1,    2,    3,   60,    1,    1,   46, 1010])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

In [110]:
# your code goes here
x = np.array([0,0,0,0,50,0,0,0], dtype = np.int)
x[x == 50] = 40
x

array([ 0,  0,  0,  0, 40,  0,  0,  0])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [115]:
# your code goes here
x = np.zeros(shape=(3,3), dtype = np.int)
x[-1] = np.ones(3)
x

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [116]:
# your code goes here
x = np.ones(shape=(3,3), dtype = np.int)
x[-1,-1] = 0
x

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [117]:
# your code goes here
x = np.ones(shape=(6,6), dtype = np.int)
x = x + 5
x

array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [123]:
# your code goes here
x = np.array([1,2,3,-4,5,6,-7,8,-9,10,-11,-12], dtype = np.int)

##Mask
mask = x < 0
#applied 
x_neg = x[mask]
x_neg

array([ -4,  -7,  -9, -11, -12])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [124]:
# your code goes here
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12], dtype = np.int)
x_higher = x[x > 5]
x_higher

array([ 6,  7,  8,  9, 10, 11, 12])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [125]:
# your code goes here
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12], dtype = np.int)
y = x[x > x.mean()]
y

array([ 7,  8,  9, 10, 11, 12])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [130]:
# your code goes here
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12], dtype = np.int)
y = x[(x==2) | (x==10)]
y

array([ 2, 10])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [145]:
# your code goes here
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12], dtype = np.int)
x.all() #all() returns True if he dosent find a False (False=0)


True

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is zero

In [147]:
# your code goes here
x = np.array([0,2,4,0,1], dtype = np.int)
x.any() #.any() returns True if he finds at least one False (False=0)

True

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [148]:
# your code goes here
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
X.sum()

43

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements

In [149]:
# your code goes here
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
X.mean()

4.777777777777778

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

In [158]:
# your code goes here
mat = np.array(
    [[3, 5, 6],
     [7, 2, 3], 
     [4, 9, 4]
     ])
mat.sum(axis=0) #axis 0 = columns, axis = 1 rows!

array([14, 16, 13])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its rows

In [159]:
# your code goes here
mat = np.array(
    [[3, 5, 6],
     [7, 2, 3], 
     [4, 9, 4]
     ])
mat.mean(axis=1)

array([4.66666667, 4.        , 5.66666667])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [161]:
# your code goes here
x = np.array([1,2,3,45,6])
x.max()

45

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)